INSERT INTO USER_ACCOUNT (ID, CREATED, FIRST_NAME, LAST_NAME, NICK, UPDATED, PASSWORD, EMAIL)
VALUES (1, '2022-10-10', 'Joe', 'Doe', 'joedoe', '2022-10-10',
        '$2a$12$AiTggCSWkKAcUBBmfqXVdeGUVmJjY5P9BBdH80joD1X2Q6v/b7HvW', 'joedoe@pwpo.com');

INSERT INTO USER_ACCOUNT (ID, CREATED, FIRST_NAME, LAST_NAME, NICK, UPDATED, PASSWORD, EMAIL)
VALUES (2, '2022-10-10', 'Max', 'Musserman', 'maxmusserman', '2022-10-10',
        '$2a$12$kR4wt7GSk9Q5ay.hthSkGe8cA5mLfXn0FRyRxC/ab9viF.LttV7j2', 'maxmusserman@pwpo.com');

INSERT INTO USER_ACCOUNT (ID, CREATED, FIRST_NAME, LAST_NAME, NICK, UPDATED, PASSWORD, EMAIL)
VALUES (3, '2022-10-10', 'Tom', 'Smith', 'tomsmith', '2022-10-10',
        '$2a$10$msMkxMCSbrxrmc67J7gk8.B98Gw66yfrr.Y/TtR8SBcpnnCoLepcW', 'tomsmith@pwpo.com');

INSERT INTO USER_ACCOUNT (ID, CREATED, FIRST_NAME, LAST_NAME, NICK, UPDATED, PASSWORD, EMAIL)
VALUES (4, '2022-10-10', 'Admin', '', 'admin', '2022-10-10',
        '$2a$12$kxaN6ZP9jrpAULlEmkjeKujPfgmf.LGV52ttLsWgdB.racbKK2QKa', 'admin@pwpo.com');

INSERT INTO USER_ACCOUNT (ID, CREATED, FIRST_NAME, LAST_NAME, NICK, UPDATED, PASSWORD, EMAIL)
VALUES (5, '2022-10-10', 'John', 'Smith', 'johnsmith', '2022-10-10',
        '$2a$12$qylTdRmDHaDDDxOX5g1noeAUmxBbr3EaEdNGly/RXarF353J7squG', 'johnsmith@pwpo.com');

INSERT INTO USER_ACCOUNT (ID, CREATED, FIRST_NAME, LAST_NAME, NICK, UPDATED, PASSWORD, EMAIL)
VALUES (6, '2022-10-10', 'Tom', 'Doe', 'tomdoe', '2022-10-10',
        '$$2a$12$NKKeDipKJaGXmhHEFJofPuTYc6asMyXtVXhwpLLw6ZtzzJpuy7Nue', 'tomdoe@pwpo.com');

INSERT INTO USER_ACCOUNT (ID, CREATED, FIRST_NAME, LAST_NAME, NICK, UPDATED, PASSWORD, EMAIL)
VALUES (7, '2022-10-10', 'Luk', 'Shek', 'vnhk', '2022-10-10',
        '$2a$12$KZN/kKFvE8k0RxIpIuETcu7GnuzsMA27yFTtnAoBS6QFMrxkbU.Oi', 'vnhk@pwpo.com');

INSERT INTO ACCOUNT_ROLE (USER_ACCOUNT_ID, ROLE)
VALUES (1, 'ROLE_USER');
INSERT INTO ACCOUNT_ROLE (USER_ACCOUNT_ID, ROLE)
VALUES (2, 'ROLE_MANAGER');
INSERT INTO ACCOUNT_ROLE (USER_ACCOUNT_ID, ROLE)
VALUES (3, 'ROLE_USER');
INSERT INTO ACCOUNT_ROLE (USER_ACCOUNT_ID, ROLE)
VALUES (4, 'ROLE_ADMIN');
INSERT INTO ACCOUNT_ROLE (USER_ACCOUNT_ID, ROLE)
VALUES (5, 'ROLE_NOT_ACTIVATED');
INSERT INTO ACCOUNT_ROLE (USER_ACCOUNT_ID, ROLE)
VALUES (5, 'ROLE_USER');
INSERT INTO ACCOUNT_ROLE (USER_ACCOUNT_ID, ROLE)
VALUES (6, 'ROLE_MANAGER');
INSERT INTO ACCOUNT_ROLE (USER_ACCOUNT_ID, ROLE)
VALUES (7, 'ROLE_ADMIN');
INSERT INTO ACCOUNT_ROLE (USER_ACCOUNT_ID, ROLE)
VALUES (7, 'ROLE_SUPER_ADMIN');
INSERT INTO ACCOUNT_ROLE (USER_ACCOUNT_ID, ROLE)
VALUES (7, 'ROLE_MANAGER');