INSERT INTO PROJECT (ID, CREATED, NAME, DESCRIPTION, SHORT_FORM, STATUS, SUMMARY, CREATED_BY_ID, OWNER_ID, UPDATED)
VALUES (3, '2023-01-01', 'TowerFence',
        'TowerFence is a tower defense game that challenges players to protect their base from waves of enemy attacks. The game is set in a fictional world where players take on the role of a commander, tasked with strategically placing various types of defensive towers and obstacles to fend off the enemy. The game features a range of different tower types, each with unique abilities and strengths, that players can strategically place along the path of the enemy''s advance to slow or damage their progress. In addition to towers, players can also deploy traps and obstacles that can block the enemy''s advance or cause damage.',
        'TF', 'NEW',
        'TowerFence is a challenging and engaging tower defense game that combines strategy and resource management', 6,
        2, NOW());

INSERT INTO USER_PROJECT (ID, PROJECT_ID, USER_ID, ROLE, CREATED, UPDATED)
VALUES (300, 3, 2, 'PRODUCT_OWNER', '2023-01-01', '2023-01-01');

INSERT INTO TASK (ID, CREATED, DESCRIPTION, DUE_DATE, ESTIMATION, NUMBER, PRIORITY, STATUS, SUMMARY, TYPE, ASSIGNEE_ID,
                  CREATED_BY_ID, OWNER_ID, PROJECT_ID, UPDATED)
VALUES (300, '2023-01-01',
        'This task involves the creation of a unique game idea and the development of gameplay mechanics that will bring the game concept to life. The team must brainstorm and research ideas, identify target audience, and create a design plan. The mechanics should be carefully crafted to create an immersive and engaging gaming experience for players.',
        '2023-01-15', 480, 'TF-1829', 'HIGH', 'NEW',
        'Game concept and mechanics', 'OBJECTIVE', 6, 2, 6, 3, NOW()),
       (301, '2023-01-02',
        'Create game design document - This task involves the creation of a comprehensive design document that outlines the game concept, mechanics, story, level design, user interface, art style, and sound design. The document serves as a guide for the development team and helps to ensure that everyone is on the same page with regards to the vision and direction of the game.',
        '2023-01-20', 720, 'TF-9127', 'CRITICAL', 'NEW',
        'Game design document', 'STORY', 2, 2, 2, 3, NOW()),
       (302, '2023-01-03',
        'This task involves the creation of the game engine, which is the software framework that supports the game''s mechanics, physics, graphics, and other features. The development team must select an appropriate game engine, set up the development environment, and create the necessary code and scripts to bring the game to life.',
        '2023-02-15', 960, 'TF-6342', 'CRITICAL', 'NEW',
        'Game engine development', 'FEATURE', 6, 2, 6, 3, NOW()),
       (303, '2023-01-04',
        'This task involves the creation of the various levels that players will navigate through as they progress through the game. The team must create detailed level designs, including layouts, environmental hazards, and enemy placement. The levels should be balanced to provide a challenging but rewarding experience for players.',
        '2023-02-28', 720, 'TF-3985', 'HIGH', 'NEW', 'Game level design',
        'STORY',
        NULL, 2, 6, 3, NOW()),
       (304, '2023-01-05',
        'This task involves the creation of the game''s visual and audio assets, including character models, textures, backgrounds, and sound effects. The team must work together to ensure that the game''s art style is consistent and appealing to players.',
        '2023-02-28', 1200, 'TF-7506', 'CRITICAL', 'NEW',
        'Game art and sound assets creation', 'OBJECTIVE', 2, 2, 2, 3, NOW()),
       (305, '2023-01-06',
        'This task involves writing the code and scripts that control the game''s mechanics, physics, and other features. The team must work together to ensure that the game logic is stable and bug-free.',
        '2023-03-15', 1440, 'TF-2948', 'HIGH', 'NEW',
        'Game logic implementation',
        'TASK', 6, 2, 6, 3, NOW()),
       (306, '2023-01-07',
        'This task involves testing the game mechanics to ensure that they function as intended. The team must identify and fix any bugs or issues that are discovered during testing.',
        '2023-03-31', 480, 'TF-7351', 'MEDIUM', 'NEW',
        'Game mechanics testing',
        'TASK', 2, 2, 2, 3, NOW()),
       (307, '2023-01-08',
        'This task involves the creation of the game''s various enemy characters, including their visual design, behavior, and abilities. The team must work together to ensure that the enemies are challenging but not frustrating for players to fight against.',
        '2023-04-15', 960, 'TF-6795', 'HIGH', 'NEW',
        'Enemy character creation',
        'FEATURE', NULL, 6, 2, 3, NOW()),
       (308, '2023-01-09',
        'This task involves the creation of the game''s boss characters, which are more powerful enemies that serve as major challenges for players to overcome. The team must work together to ensure that the bosses are challenging but not impossible to defeat.',
        '2023-04-30', 720, 'TF-4065', 'HIGH', 'NEW',
        'Boss character creation',
        'STORY', 2, 2, 6, 3, NOW()),
       (309, '2023-01-10',
        'This task involves designing and implementing the game''s user interface, including menus, HUD elements, and other visual indicators that help players navigate the game. The team must work together to ensure that the UI is intuitive and easy to use.',
        '2023-05-15', 720, 'TF-9367', 'MEDIUM', 'NEW',
        'Game user interface creation',
        'TASK', NULL, 6, 2, 3, NOW()),
       (310, '2023-01-11',
        'This task involves adjusting the game''s difficulty to ensure that it provides an appropriate level of challenge for players. The team must playtest the game extensively and make adjustments as necessary to ensure that the game is both fun and challenging.',
        '2023-05-31', 480, 'TF-1549', 'MEDIUM', 'NEW',
        'Game difficulty balancing', 'TASK', 2, 2, 6, 3, NOW());


INSERT INTO TASK (ID, CREATED, DESCRIPTION,
                  DUE_DATE, ESTIMATION, NUMBER,
                  PRIORITY, STATUS, SUMMARY, TYPE, ASSIGNEE_ID,
                  CREATED_BY_ID, OWNER_ID, PROJECT_ID, UPDATED)
VALUES (311, '2023-05-15',
        'This task involves refining the game''s level designs and mechanics based on feedback from playtesting. The team must work together to ensure that the game''s levels and mechanics are fun and engaging.',
        '2023-06-30', 1440, 'TF-3657', 'MEDIUM', 'NEW',
        'Game design', 'OBJECTIVE', '2', '2', '6', '3', '2023-05-15'),
       (312, '2023-05-15',
        'This task involves writing the code and scripts that control the behavior of the game''s enemy characters. The team must work together to ensure that the AI is challenging but not frustrating for players to fight against.',
        '2023-07-15', 720, 'TF-7436', 'HIGH', 'NEW', 'Enemy AI',
        'TASK', NULL, '2', '6', '3', '2023-05-15'),
       (313, '2023-05-15',
        'Create sound effects and music: Sound effects and music play a critical role in creating an immersive gaming experience. This task involves creating and implementing high-quality sound effects and music that complement the game''s style and narrative. The designers will need to work closely with the game''s audio engineers to ensure that the sound effects and music are optimized for the game''s performance.',
        '2023-08-01', 600, 'TF-2359', 'MEDIUM', 'NEW',
        'Audio assets', 'STORY', '6', '2', '6', '3', '2023-05-15'),
       (314, '2023-05-15',
        'Adding multiplayer functionality to a game can significantly enhance its replayability and social aspects. This task involves designing and implementing the game''s multiplayer functionality, including matchmaking, online play, and leaderboards. The designers will need to work closely with the game''s programmers and network engineers to ensure that the multiplayer functionality is stable and optimized for the game''s performance.',
        '2023-08-15', 960, 'TF-6523', 'HIGH', 'NEW',
        'Multiplayer', 'FEATURE', '6', '2', '6', '3', '2023-05-15'),
       (315, '2023-05-15',
        'This task involves rigorous testing of the game mechanics to identify any bugs or issues that may arise during gameplay. It involves creating test cases and testing each aspect of the game thoroughly. The goal is to ensure that the game is stable and free of any major issues that could cause it to crash or malfunction.',
        '2023-08-30', 480, 'TF-9812', 'LOW', 'NEW', 'Testing',
        'TASK', NULL, '2', '6', '3', '2023-05-15'),
       (316, '2023-05-15',
        'This task involves creating game art assets such as character sprites, environment assets, and other visual elements. The assets must be designed to fit the game concept and mechanics. The artist must follow the art style guide and ensure that the assets are high-quality and consistent in style. The assets must also be optimized for performance and be delivered in the appropriate file formats and resolutions.',
        '2023-09-15', 1800, 'TF-1476', 'HIGH', 'NEW', 'Art assets',
        'OBJECTIVE', '2', '2', '6', '3', '2023-05-15'),
       (317, '2023-05-15',
        'This task involves implementing the ability for players to build and upgrade towers in the game. The towers must have unique characteristics and abilities, and players should be able to upgrade them to increase their power and effectiveness. The implementation must consider factors such as cost, range, and damage, and should be balanced to ensure a fair gameplay experience.',
        '2023-09-30', 720, 'TF-5678', 'MEDIUM', 'NEW',
        'Towers', 'FEATURE', '6', '2', '6', '3', '2023-05-15'),
       (318, '2023-05-15',
        'This task involves improving the game''s performance by reducing lag, improving loading times, and optimizing resource usage. The optimization must be done without sacrificing the game''s visual quality or gameplay experience. The developer must identify and address any bottlenecks or inefficiencies in the game code, and must test the game across a range of devices and platforms to ensure optimal performance.',
        '2023-10-15', 960, 'TF-1209', 'HIGH', 'NEW', 'Performance',
        'TASK', NULL, '2', '6', '3', '2023-05-15'),
       (319, '2023-05-15',
        'This task involves creating tutorial and help screens to guide players through the game mechanics and features. The screens should be user-friendly, engaging, and informative, and should be designed to match the game''s visual style. The content should be easy to understand and cover all necessary aspects of the game, including controls, objectives, and tips and tricks.',
        '2023-11-01', 480, 'TF-9876', 'MEDIUM', 'NEW',
        'Help screens', 'STORY', '2', '2', '6', '3', '2023-05-15'),
       (320, '2023-05-15',
        'This task involves implementing an in-game store where players can purchase virtual items, upgrades, or other content using real money or in-game currency. The implementation must follow industry standards and best practices for security and user data privacy. The developer must also ensure that the store is balanced and does not give players who spend money an unfair advantage over those who do not. The transactions must be seamless and user-friendly, and the store interface must match the game''s visual style.',
        '2023-11-15', 1440, 'TF-3098', 'HIGH', 'NEW',
        'In-game store', 'FEATURE', '2', '2', '6', '3', '2023-05-15');
