INSERT INTO USER_ACCOUNT (ID, CREATED, FIRST_NAME, LAST_NAME, NICK, UPDATED, PASSWORD, EMAIL)
VALUES (2, '2022-10-10', 'Joseph', 'Sherk', 'zbyszek', '2022-10-10',
        '$2a$12$kR4wt7GSk9Q5ay.hthSkGe8cA5mLfXn0FRyRxC/ab9viF.LttV7j2', 'zbyszek@pwpo.com');

INSERT INTO ACCOUNT_ROLE (USER_ACCOUNT_ID, ROLE)
VALUES (2, 'ROLE_MANAGER');
